refactor: move auth logic to hono api
daedalus-developers/hrs pull request #17
Opened 2024-06-23 08:14 UTC by gestanestle

Please review, thank you!

2024-06-23 09:27 UTC, directormac commented
@gestanestle  Thank your for this contribution although i would like to point out that it could have been easier if you used the RPC that hono give's us.

2024-06-23 09:33 UTC, directormac requested changes

2024-06-23 09:33 UTC, directormac commented on src/lib/actions/logout.ts
This can be called as


```ts
client.api.auth.logout.$get()
```


We can also let hono do the cookie deletion at hono function.

2024-06-23 09:33 UTC, directormac commented on src/lib/actions/login.ts
This can be called as
```ts
client.api.auth.login.$post({
email, 
password
})
```

2024-06-23 09:33 UTC, directormac commented on src/lib/actions/resend.ts
This can be called as
```ts
client.api.auth.resend.$post({
.... data here
})
```

2024-06-23 09:33 UTC, directormac commented on src/lib/actions/signup.ts
This can be called as
```ts
client.api.auth.signup.$post({
.... data here
})
```

2024-06-25 14:55 UTC, directormac requested changes

2024-06-25 14:55 UTC, directormac commented on src/lib/client/hono.ts
Hi Whats with the headers? i think init credentials include will suffice , looks cute tho.

2024-06-25 14:55 UTC, directormac commented on src/lib/server/auth.ts
In this cached part from react , should we use the type from lucia so we are consistent on what comes back to the nextjs side and to the client side.

2024-06-25 14:55 UTC, directormac commented on src/lib/server/schemas/user.ts
We can avoid using the pick here. if we use what we defined in the User type from lucia which in there we removed the password already. a more cleaner approach to this one also is

```ts
const selectUserPickSchema = createSelectSchema(users).omit({ password: true})
```

2024-06-25 15:58 UTC, gestanestle commented on src/lib/client/hono.ts
> Hi Whats with the headers? i think init credentials include will suffice , looks cute tho.

That was to test things out ahahaha.

2024-06-25 18:43 UTC, directormac approved these changes

2024-06-25 18:43 UTC, merged